# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embedding.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'embedding.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x65mbedding.proto\x12\tembedding\" \n\x10\x45mbeddingRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\xb2\x01\n\x11\x45mbeddingResponse\x12\x33\n\x06status\x18\x01 \x01(\x0e\x32#.embedding.EmbeddingResponse.Status\x12)\n\tembedding\x18\x02 \x01(\x0b\x32\x14.embedding.EmbeddingH\x00\x12\x0f\n\x05\x65rror\x18\x03 \x01(\tH\x00\"!\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\x42\t\n\x07payload\"\x1b\n\tEmbedding\x12\x0e\n\x06values\x18\x01 \x03(\x02\x32]\n\x10\x45mbeddingService\x12I\n\x0cGetEmbedding\x12\x1b.embedding.EmbeddingRequest\x1a\x1c.embedding.EmbeddingResponseB#\n\x0f\x65mbedding.protoB\x0e\x45mbeddingProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embedding_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\017embedding.protoB\016EmbeddingProtoP\001'
  _globals['_EMBEDDINGREQUEST']._serialized_start=30
  _globals['_EMBEDDINGREQUEST']._serialized_end=62
  _globals['_EMBEDDINGRESPONSE']._serialized_start=65
  _globals['_EMBEDDINGRESPONSE']._serialized_end=243
  _globals['_EMBEDDINGRESPONSE_STATUS']._serialized_start=199
  _globals['_EMBEDDINGRESPONSE_STATUS']._serialized_end=232
  _globals['_EMBEDDING']._serialized_start=245
  _globals['_EMBEDDING']._serialized_end=272
  _globals['_EMBEDDINGSERVICE']._serialized_start=274
  _globals['_EMBEDDINGSERVICE']._serialized_end=367
# @@protoc_insertion_point(module_scope)
