# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embed.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'embed.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65mbed.proto\x12\x05\x65mbed\"\x1c\n\x0c\x45mbedRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x9f\x01\n\rEmbedResponse\x12+\n\x06status\x18\x01 \x01(\x0e\x32\x1b.embed.EmbedResponse.Status\x12\"\n\x05\x65mbed\x18\x02 \x01(\x0b\x32\x11.embed.EmbedValueH\x00\x12\x0f\n\x05\x65rror\x18\x03 \x01(\tH\x00\"!\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\x42\t\n\x07payload\"\x1c\n\nEmbedValue\x12\x0e\n\x06values\x18\x01 \x03(\x02\x32\x45\n\x0c\x45mbedService\x12\x35\n\x08GetEmbed\x12\x13.embed.EmbedRequest\x1a\x14.embed.EmbedResponseB\x1b\n\x0b\x65mbed.protoB\nEmbedProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embed_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013embed.protoB\nEmbedProtoP\001'
  _globals['_EMBEDREQUEST']._serialized_start=22
  _globals['_EMBEDREQUEST']._serialized_end=50
  _globals['_EMBEDRESPONSE']._serialized_start=53
  _globals['_EMBEDRESPONSE']._serialized_end=212
  _globals['_EMBEDRESPONSE_STATUS']._serialized_start=168
  _globals['_EMBEDRESPONSE_STATUS']._serialized_end=201
  _globals['_EMBEDVALUE']._serialized_start=214
  _globals['_EMBEDVALUE']._serialized_end=242
  _globals['_EMBEDSERVICE']._serialized_start=244
  _globals['_EMBEDSERVICE']._serialized_end=313
# @@protoc_insertion_point(module_scope)
